version: '3'

services:
 nginx:
   build: .
   image: instagramtools/user-interface
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./build:/build
   environment:
     - DEBUG=on
     - APP_PATH_PREFIX=/aSubSiteInParentDomainUseThisPath
     - APP_API_PLACEHOLDER=/api
     - APP_API_GATEWAY=http://api:8000
     - PAYMENT_PLACEHOLDER=/pay
     - PAYMENT_GATEWAY=http://payment-manager:7000
     - CLIENT_BODY_TIMEOUT=10
     - CLIENT_HEADER_TIMEOUT=10
     - CLIENT_MAX_BODY_SIZE=1024
     - WHITE_LIST_IP=(172.17.0.1)|(192.168.0.25)
     - WHITE_LIST=off
     - PROVIDER=cloudflare
     - LEXICON_CLOUDFLARE_USERNAME=yourcloudflarelogin@example.com
     - LEXICON_CLOUDFLARE_TOKEN=1231231231321321321321321321321321
     - UI_SERVER_NAME=localhost
     - MAILTO=info@example.com

   depends_on:
     - api
     - payment-manager
   links:
     - api:api
     - payment-manager:payment-manager

 payment-manager:
   image: instagramtools/payment-manager
   ports:
   - "7000:7000"

 api:
    image: instagramtools/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DEBUG=True
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - PATH_TO_SSH_KEY=tk
      - SSH_PORT=tk
      - IP=tk
      - SECURITY_PASSWORD_SALT=tk
 postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  db_data: